[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.dependencies]
minecrust_protocol = { path = "./crates/protocol" }
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
pin-project-lite = "0.2.16"
etcd-client = "0.17.0"
tokio-util = { version = "0.7.17", features = ["rt"] }
thiserror = "2.0.17"
arc-swap = "1.7.1"
tracing = "0.1.43"
bytes = "1.11.0"
tokio = "1.48.0"
