[package]
name = "minecrust_protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
minecrust_protocol_macro = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
bytes = { workspace = true }
uuid = { workspace = true }
